import type { Metadata } from "next";
import { Inter, K2D, Abel } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const k2d = K2D({
  subsets: ["latin"],
  weight: ["100", "200", "300"],
  variable: "--font-k2d",
});
const abel = Abel({
  subsets: ["latin"],
  variable: "--font-abel",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={k2d.variable + " " + abel.variable}>{children}</body>
    </html>
  );
}
